services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /mnt/nextcloud:/var/www/html
    env_file: .env
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
    depends_on:
      - nextcloud-db
    networks:
      - home-net

  nextcloud-db:
    image: postgres:16.8-alpine3.20
    container_name: nextcloud-db
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    networks:
      - home-net

volumes:
  nextcloud-db:

networks:
  home-net:
    external: true