---
- name: Install Docker
  shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add current user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
