{
 "title": "SNMP Mikrotik Data Stats",
 "description": "For snmp_exporter IF-MIB & MIb",
 "tags": [
  "snmp_exporter",
  "Mikrotik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Job", "query": { "query": "label_values(ifHCInOctets,job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysUpTime{job='$Job'}/100" }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(8 * irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(8 * irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "Bandwidth Metrics (bits)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "8 * irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "8 * irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "8 * irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "8 * -irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  { "title": "Bandwidth Metrics (bytes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}