{
 "title": "SNMP Mikrotik",
 "description": "Mikrotik monitoring",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp_exporter",
  "snmp v2c"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets{job=\"mikrotik\"},instance)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Mikrotik",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "up{job='mikrotik'}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Uptime Tunnels of $instance",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ifOperStatus{job='mikrotik',instance= \"$instance\" }",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  { "title": "SNMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total SNMP time (walk and processing)",
   "type": "stat",
   "description": "Total SNMP time scrape took (walk and processing)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Time SNMP walk/bulkwalk took",
   "type": "stat",
   "description": "Time SNMP walk/bulkwalk took",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "scrape pdus returned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  {
   "title": "HOLA!",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "options": {
    "content": "# Sam Goldi Mikrotik Home Server"
   }
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "Status device",
   "type": "stat",
   "description": "The current operational state of the device described by this row of the table. A value unknown(1) indicates that the current state of the device is unknown. running(2) indicates that the device is up and running and that no unusual error conditions are known. The warning(3) state indicates that agent has been informed of an unusual error condition by the operational software (e.g., a disk device driver) but that the device is still 'operational'. An example would be a high number of soft errors on a disk. A value of testing(4), indicates that the device is not available for use because it is in the testing state. The state of down(5) is used only when the agent has been informed that the device is not available for any use.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceStatus{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "System identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysIdentity{instance='$instance'}",
     "legendFormat": "{{sysIdentity}}"
    }
   ]
  },
  {
   "title": "Software ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicSoftwareId{instance='$instance'}",
     "legendFormat": "{{mtxrLicSoftwareId}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "CPU {{hrDeviceIndex}}  load"
    },
    {
     "expr": "mtxrHlTemperature{instance='$instance'}/10",
     "legendFormat": "CPU temp"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    },
    {
     "expr": "mtxrHlVoltage{instance='$instance'}/10",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "System date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(hrSystemDate{instance='$instance'})"
    }
   ]
  },
  {
   "title": "Package ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrLicVersion{instance='$instance'}",
     "legendFormat": "{{mtxrLicVersion}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "Device Errors",
   "type": "stat",
   "description": "The number of errors detected on this device",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceErrors{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})"
    }
   ]
  },
  {
   "title": "RAM load ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "system disk load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "License level",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicLevel{instance='$instance'}",
     "legendFormat": "Lic"
    },
    {
     "expr": "mtxrLicUpgradableTo{instance='$instance'}",
     "legendFormat": "Upgradable to"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    },
    { "expr": "ifMtu{instance='$instance'}" },
    {
     "expr": "ifType_info{instance='$instance'}"
    },
    {
     "expr": "mtxrPOEInterfaceIndex{instance='$instance'}"
    },
    { "expr": "ifAlias{instance='$instance'}" }
   ]
  }
 ]
}